### ISSUE TITLE
User server can't start without main.py

### ISSUE THREAD

**Issue by manuIO** [nodesign/weio#42] opened 2014-11-19 08:18 UTC
Even if main.py is empty user server can't start, the log is: "main.py don't exist!"
It could be more helpful and understandable for beginners if is not necessary to create an empty main.py file in the project.

**Comment by manuIO** [comment] 2015-03-03 05:36
I've tried that and it works for me:
https://github.com/nodesign/weio/pull/143

**Comment by ks156** [comment] 2015-04-17 19:27
I confirm the fix with PR #143

**Comment by ks156** [comment] 2015-04-17 21:49
I reopen it, because I don't understand something.
It indeed works without main.py. But once the project is started, main.py is created and a message is displayed in the console.
https://github.com/nodesign/weio/blob/master/weioPlayer.py#L144-L148

If it's the normal and expected behavior, please close it again.

**Comment by manuIO** [comment] 2015-04-18 10:44
It's strange because I've removed this lines in my commit: https://github.com/manuIO/weio/commit/aa27fabf7fd29f1bfe947c27492197a987eaf39f#diff-5a781d5384ef176158ead116691b39e9L148

**Comment by manuIO** [comment] 2015-04-18 10:50
It seems like @drasko have only merged last commit of pull request (there is 3 commits in PR https://github.com/nodesign/weio/pull/143)

**Comment by manuIO** [comment] 2015-04-18 12:08
I've done modifications manually 
Here is new PR: https://github.com/manuIO/weio/commit/c313a2b8f0396506880d7058c099167e8119a534
And here last @ukicar commit that I've accidentally removed: https://github.com/nodesign/weio/pull/182

**Comment by ks156** [comment] 2015-04-18 18:05
Ok, I'll test it tonight

**Comment by ks156** [comment] 2015-04-18 19:47
Excepted the debug message (*WARNING: Using WeIO default main.py (www/defaultMain/main.py)*), it's OK for me.
This message is useless imho

**Comment by ks156** [comment] 2015-05-12 19:43
Tested and confirmed. OK

**Comment by manuIO** [comment] 2015-05-13 06:38
Tested and confirmed. :+1:

**Closed** 2015-05-14 09:59 UTC
Labels: enhancement, Fixed
