### ISSUE TITLE
Bug in parameter Switch automatically to AP if STA network is not found or broken

### ISSUE THREAD

**Issue by ukicar** [nodesign/weio#172] opened 2015-04-17 13:41 UTC
Checkbox has never been cabled behind for this functionality. This is the place where variable comes from IDE : https://github.com/nodesign/weio/blob/master/handlers/userSettingsHandler.py#L121

But in config.weio there is nothing called auto_to_ap
To resolve this issue we have to 
- add "auto_to_ap" option in config.weio and set it to YES
- edit this block of code to insert auto_to_ap detection and then retry to go to STA if network is broken https://github.com/nodesign/weio/blob/master/weioWifi/weioWifi.py#L110-L126

**Comment by ks156** [comment] 2015-10-17 19:55
@ukicar Please confirm this fix and close the issue if OK

**Comment by drasko** [comment] 2015-10-19 19:02
@ukicar action from you needed!

**Comment by ks156** [comment] 2015-10-20 05:43
Fix confirmed by @manuIO (email)

**Comment by ks156** [comment] 2015-11-01 13:17
The original fix works if the connection is lost when the board is powered.
But if the STA network is not available at system boot, it fall back in AP mode.

From my point of view, the system must stays waiting for the STA network in this case. For example, after a power cut, home routers are often longer to boot than WeIO, and falling back to AP is probably not the intended behavior.

**Comment by ks156** [comment] 2015-11-01 18:34
I propose to transform this part https://github.com/nodesign/weio/blob/master/scripts/run_weio.sh#L118-L127 by : 
````bash
if grep -q '"auto_to_ap": "YES"' /weio/config.weio; then
    while [ $WIFI_READY -ne 1 ]; do
        echo "WiFi network is not ready. Switching to RESCUE mode."

        # We did not connect even after whole delay expired
        # Something went wrong - got to RESCUE
        /weio/scripts/wifi_set_mode.sh rescue

        # Re-check WiFi
        check_wifi
    done
fi
```
to prevent an auto reconfiguration if ```auto_to_ap``` is not set and the wifi network is not available at boot start.

@ukicar, @drasko, ok with that ?

**Comment by drasko** [comment] 2015-11-01 22:20
OK for me. Note - if for some reason you can not log in as a STA (for example typo in the password), you will not come back to AP mode. This will demand manual network set-up, and after that restart of WeIO app.

But this is OK for me, as I suppose that `auto_to_ap : NO` is for advanced users.

**Comment by ks156** [comment] 2015-11-02 10:12
Yeah, but there's a button to fall back in AP if needed.
I'll do the change tonight.

**Comment by drasko** [comment] 2015-11-02 10:13
OK, +1

**Comment by ks156** [comment] 2015-11-02 19:26
PR #260 merged, and fully tested on my side.
Can be closed once the fix is confirmed by someone else.

**Closed** 2016-01-14 19:00 UTC
Labels: bug, Fixed
